# -*- encoding : utf-8 -*-
require 'savon'
require 'rs/version'
require 'rs/base'
require 'rs/vat'
require 'rs/initializable'
require 'rs/sys'
require 'rs/dict'
require 'rs/waybill'
require 'rs/factura'
